[package]
name = "sixaxis_rs"
version = "1.0.1"
edition = "2021"

[profile.release]
lto = true

[dependencies]
futures-lite = "2.5"
macaddr = "1.0"
nusb = "0.1"
owo-colors = { version = "4.1", features = ["supports-colors"] }
